---
- name: Cisco ACI Ansible
  hosts: routers
  gather_facts: false

  tasks:
    # Create tenant
    - name: Create tenant
      cisco.aci.aci_tenant:
        host: "{{ _host_ }}"
        username: "{{ _username_ }}"
        password: "{{ _password_ }}"
        validate_certs: "{{ _validate_certs_ }}"
        use_ssl: "{{ _use_ssl_ }}"
        use_proxy: "{{ _use_proxy_ }}"
        output_level: debug
        tenant: ansible_test
        state: present
      register: tenant_present
    
    
    # create VRF & create BD
    - name: Create VRF
      cisco.aci.aci_vrf:
        host: "{{ _host_ }}"
        username: "{{ _username_ }}"
        password: "{{ _password_ }}"
        validate_certs: "{{ _validate_certs_ }}"
        use_ssl: "{{ _use_ssl_ }}"
        use_proxy: "{{ _use_proxy_ }}"
        output_level: debug
        tenant: ansible_test
        state: present
        vrf: ansible_test
      register: vrf_present
    
    - name: Create BD
      cisco.aci.aci_bd:
        host: "{{ _host_ }}"
        username: "{{ _username_ }}"
        password: "{{ _password_ }}"
        validate_certs: "{{ _validate_certs_ }}"
        use_ssl: "{{ _use_ssl_ }}"
        use_proxy: "{{ _use_proxy_ }}"
        output_level: debug
        tenant: ansible_test
        state: present
        bd: ansible_test
      register: bd_present
    
 