---
- name: Create Resource Group
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group_name | default('demo') }}"
        location: "{{ region }}"

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group_name | default('demo') }}"
        name: "{{ vnet_name }}"
        address_prefixes: "{{ vnet_cidr }}"

    - name: Add subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group_name | default('demo') }}"
        name: "{{ subnet_name }}"
        address_prefix: "{{ subnet_cidr }}"
        virtual_network: "{{ vnet_name }}"

    - name: Create Network Security Group that allows SSH and RDP
      azure_rm_securitygroup:
        resource_group: "{{ resource_group_name | default('demo') }}"
        name: "{{ network_sec_group_name }}"
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
          - name: RDP
            protocol: Tcp
            destination_port_range: 3389
            access: Allow
            priority: 1002
            direction: Inbound
