---
- name: Create Azure Resource Group
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create resource Group
      # Content suggestion provided by Ansible Lightspeed
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ _name_ }}"
        location: "{{ _location_ }}"
        tags:
          testing: testing
          delete: on-exit
          foo: bar


    - name: Create virtual Network
      # Content suggestion provided by Ansible Lightspeed
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: "{{ _name_ }}"
        name: "{{ _name_ }}"
        address_prefixes: "{{ _address_prefixes_ }}"

    - name: Add subnet_cidr
      # Content suggestion provided by Ansible Lightspeed
      azure.azcollection.azure_rm_subnet:
        resource_group: "{{ _name_ }}"
        name: "{{ _name_ }}"
        address_prefix: "{{ _address_prefix_ }}"
        virtual_network: "{{ _virtual_network_ }}"

    - name: Create Network Security Group that allows SSH and RDP
      azure_rm_securitygroup:
        resource_group: "{{ resource_group_name | default('demo') }}"
        name: "{{ network_sec_group_name }}"
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
          - name: RDP
            protocol: Tcp
            destination_port_range: 3389
            access: Allow
            priority: 1002
            direction: Inbound
