---
- name: Apache server installed
  hosts: web
  become: true
  tasks:

    - name: Install apache
      ansible.builtin.package:
        name: apache2
        state: present



    - name: Copy index.html
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/






    # Enable apache service & Allow http through firewall
    - name: Enable apache service
      ansible.builtin.service:
        name: apache2
        enabled: true
        state: started

    - name: Allow http through firewall
      community.general.ufw:
        rule: allow
        port: '80'
        proto: tcp






