---
- name: Apache server installed
  hosts: web
  become: true
  tasks:

    # install web server on rhel
    - name: Install web server on rhel
      when: ansible_os_family == "RedHat"
      ansible.builtin.package:
        name: httpd
        state: present



    # Copy index.html & enable httpd service & allow http through firewall
    - name: Copy index.html
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/

    - name: Enable httpd service
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started

    - name: Allow http through firewall
      when: ansible_os_family == "RedHat"
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled




 
     