---
- name: Apache server installed
  hosts: web
  become: true
  tasks:
 
     # Install apache
      - name: Install apache
         ansible.builtin.package:
         name: apache2
         state: present
     
     
     # copy index.html & enable apache service & allow http through firewall
  