---
- name: Apache server installed
  hosts: web
  become: true
  tasks:
  - name: latest httpd version installed
    ansible.builtin.package:
      name: httpd
      state: latest

  - name: copy index.html
    ansible.builtin.copy:
      src: files/index.html
      dest: /var/www/html/index.html

  - name: Apache enabled and running
    ansible.builtin.service:
      name: httpd
      enabled: true
      state: started

  - name: Allow http through firewall
    ansible.posix.firewalld:
      service: http
      permanent: true
      state: enabled