---
- name: Deploy monitoring
  hosts: monitoring
  become: true

  # module_defaults:
  #   ansible.builtin.service:
  #     enabled: true
  #     state: started

  tasks:
    - name: Include redhat.rhel_system_roles.cockpit

    
    - name: Copy files/cockpit.conf to /etc/cockpit/


    
    - name: Restart cockpit service

    

    
    - name: Allow cockpit through firewall
 

    
    

    
    
