---
- name: Apache server installed
  hosts: web
  become: true
  tasks:

  - name: latest httpd version installed
    ansible.builtin.package:
      name: httpd
      state: latest

  - name: Apache enabled and running
    ansible.builtin.service:
      name: httpd
      enabled: true
      state: started

  - name: copy index.html
    ansible.builtin.copy:
      src: index.html
      dest: /var/www/html/index.html
      owner: apache
      group: apache
      mode: '0644'
  
  - 