---
- name: Update HashiCorp Vault Secret
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    update_username: "testuser1"
    update_password: "password1"

  tasks:
    - name: Write a value to the cubbyhole via the remote host with userpass auth
      community.hashi_vault.vault_write:
        url: https://192.168.67.27:8200
        path: cubbyhole/1041
        data:
          username: "{{ update_username }}"
          password: "{{ update_password }}"
        token: "hvs.kc2B0aXPaFMzbsdjACoyjCIM"
      register: result

    - name: Display the result of the write (this can be empty)
      ansible.builtin.debug:
        msg: "{{ result.data }}"