---
- name: update rhel password
  hosts: servers
  become: true
  
  vars:
     username: ansible
     new_password: password123


  tasks:

    # update user password
    # Content suggestion provided by Ansible Lightspeed
    - name: Update user password
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ _password_ }}"


