---
- name: update rhel password
  hosts: update_servers
  become: true

  vars:
  #   username : "user1"
  #   password : "pass1"
    # update_username: "testroot1"
  #   update_password: "password1"

  tasks:
    
    # update user password
    # Content suggestion provided by Ansible Lightspeed
    - name: Update user password
      ansible.builtin.user:
        name: "{{ _name_ }}"
        password: "{{ _password_ }}"




