---
- name: update rhel password
  hosts: update_servers
  become: true



  tasks:
    
    # Print User Pass and its updates
    - name: Print User Pass and updated user pass
      ansible.builtin.debug:
        msg: 
          - "username {{ username | default('user1') }}"
          - "password {{ password | default('pass1') }}"
          - "update_username {{ update_username | default('testroot1') }}"
          - "update_password {{ update_password | default('password1') }}"
    
    # update user password
    # Content suggestion provided by Ansible Lightspeed
    - name: Update user password
      ansible.builtin.user:
        name: "{{ update_username | default('testroot1') }}"
        password: "{{ update_password | default('password1') | password_hash('sha512')  }}"
