---
- name: Update HashiCorp Vault Secret using uri module (Vault v2)
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Set Vault address and token
      set_fact:
        vault_address: "http://192.168.67.27:8200"
        vault_token: "hvs.kc2B0aXPaFMzbsdjACoyjCIM"
        new_username: "testroot1"
        new_password: "password1"

    - name: Update secret in Vault
      uri:
        url: "{{ vault_address }}/v1/cubbyhole/1041"
        method: POST
        headers:
          X-Vault-Token: "{{ vault_token }}"
        body_format: json
        body:
          {
            username: "{{ new_username }}",
            password: "{{ new_password }}"
          }
        status_code: 204
      register: vault_result

    - name: Print Vault result
      debug:
        var: vault_result