---
- name: update rhel password
  hosts: servers
  become: true
  
  vars:
     username: ansible
     new_password: password123


  tasks:
    # pre tasks
    # Content suggestion provided by Ansible Lightspeed
    - name: Pre tasks
      ansible.builtin.debug:
        msg: Pre tasks section

    # update user password
    # Content suggestion provided by Ansible Lightspeed
    - name: Update user password
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ new_password | password_hash('sha512')  }}"

    # post tasks
    # Content suggestion provided by Ansible Lightspeed
    - name: Post tasks
      ansible.builtin.debug:
        msg: post tasks section

